---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

components:
  - ./metadata
  - ./requirements
  - ../../components/tpm
  - ../../components/secureboot

nameSuffix: ".10"
