---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: cpu-topology-spread
spec:
  cpu:
    preferredCPUTopology: preferSpread
    spreadOptions:
      across: SocketsCoresThreads
      ratio: 4
